namespace ManagedLib.LanguageModel.Abstractions;

public abstract class LlmTransaction
{
    /// <summary>
    /// The request sent to the language model (LLM).
    /// This property is primarily used for debugging purposes.
    /// </summary>
    public string Request { get; set; }

    /// <summary>
    /// The response received from the language model (LLM).
    /// This property is primarily used for debugging purposes.
    /// </summary>
    public string Response { get; set; }

    /// <summary>
    /// Extracts the primary message generated by the language model 
    /// as the result of the current invocation.
    /// </summary>
    /// <returns>
    /// The answer generated by the LLM.
    /// </returns>
    public abstract string ExtractReply();
}