name: Publish to Github NuGet Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # Needed for GitHub Packages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore ManagedLib.LanguageModel.csproj
        
      - name: Build
        run: dotnet build ManagedLib.LanguageModel.csproj --configuration Release --no-restore
        
      - name: Pack
        run: dotnet pack ManagedLib.LanguageModel.csproj --configuration Release --no-build --output nupkgs
        
      - name: Publish to GitHub Packages
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/farazzbhn/index.json" 